# Generated by Django 4.0.5 on 2022-06-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('annual_leave', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=25)),
                ('tckn', models.IntegerField()),
                ('birth_date', models.DateField(max_length=25)),
                ('start_date', models.DateField(max_length=25)),
                ('admins', models.ManyToManyField(to='app.admin')),
            ],
        ),
        migrations.CreateModel(
            name='OldForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=25)),
                ('annual_leave', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualLeaveForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=25)),
                ('annual_leave', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
