# Generated by Django 4.0.5 on 2022-06-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonelDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personelid', models.IntegerField()),
                ('tckn', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('sgk', models.IntegerField()),
                ('bloodtype', models.CharField(max_length=25)),
                ('fathername', models.CharField(max_length=25)),
                ('mothername', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=25)),
                ('birthplace', models.CharField(max_length=25)),
                ('birthdate', models.CharField(max_length=25)),
                ('province', models.CharField(max_length=25)),
                ('militarystatus', models.CharField(max_length=25)),
                ('school', models.CharField(max_length=25)),
                ('department', models.CharField(max_length=25)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
