# Generated by Django 4.0.5 on 2022-07-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='izinformlaridatabase',
            old_name='personelid',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='oldformsdatabase',
            old_name='personelid',
            new_name='employee_id',
        ),
    ]
