# Generated by Django 4.0.5 on 2022-07-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualleaveform',
            old_name='dayoff',
            new_name='annual_leave',
        ),
        migrations.RenameField(
            model_name='oldformsdatabase',
            old_name='dayoff',
            new_name='annual_leave',
        ),
    ]
